declare let audioContext: AudioContext;
declare let osc1: OscillatorNode;
declare let osc2: OscillatorNode;
declare let osc3: OscillatorNode;
declare let osc4: OscillatorNode;
declare let osc1gain: GainNode;
declare let osc2gain: GainNode;
declare let osc3gain: GainNode;
declare let osc4gain: GainNode;
declare let adsr: GainNode;
declare let attackAmplitude: number;
declare let attackTime: number;
declare let decayAmplitude: number;
declare let decayTime: number;
declare let sustainTime: number;
declare let releaseTime: number;
declare let filter: BiquadFilterNode;
declare let stutter: GainNode;
declare let distortion: WaveShaperNode;
declare let delay: DelayNode;
declare let reverb: ConvolverNode;
declare let master: GainNode;
declare function makeDistortionCurve(amount: number, sampleRate: number): Float32Array;
declare function impulseResponse(duration: number, decay: number, reverse: boolean): AudioBuffer;
declare let osc1Type: HTMLSelectElement;
declare let osc1Frequency: HTMLInputElement;
declare let osc1Detune: HTMLInputElement;
declare let osc1GainSlider: HTMLInputElement;
declare let osc1GainInput: HTMLInputElement;
declare let osc2Type: HTMLSelectElement;
declare let osc2Frequency: HTMLInputElement;
declare let osc2Detune: HTMLInputElement;
declare let osc2GainSlider: HTMLInputElement;
declare let osc2GainInput: HTMLInputElement;
declare let osc3Type: HTMLSelectElement;
declare let osc3Frequency: HTMLInputElement;
declare let osc3Detune: HTMLInputElement;
declare let osc3GainSlider: HTMLInputElement;
declare let osc3GainInput: HTMLInputElement;
declare let osc4Type: HTMLSelectElement;
declare let osc4Frequency: HTMLInputElement;
declare let osc4Detune: HTMLInputElement;
declare let osc4GainSlider: HTMLInputElement;
declare let osc4GainInput: HTMLInputElement;
declare let attackSlider: HTMLInputElement;
declare let attackInput: HTMLInputElement;
declare let decaySlider: HTMLInputElement;
declare let decayInput: HTMLInputElement;
declare let sustainSlider: HTMLInputElement;
declare let sustainInput: HTMLInputElement;
declare let releaseSlider: HTMLInputElement;
declare let releaseInput: HTMLInputElement;
declare function playC(frequency: number): void;
declare function playCD(frequency: number): void;
declare function playD(frequency: number): void;
declare function playDE(frequency: number): void;
declare function playE(frequency: number): void;
declare function playF(frequency: number): void;
declare function playFG(frequency: number): void;
declare function playG(frequency: number): void;
declare function playGA(frequency: number): void;
declare function playA(frequency: number): void;
declare function playAB(frequency: number): void;
declare function playB(frequency: number): void;
declare function play(): void;
